spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playlist?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account
  mail:
    host: smtp.gmail.com
    port: 587
    username: zhedron@gmail.com
    password: ${PASSWORD_GOOGLE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret:
    key: ${JWT_KEY}
  expiration: 604800000

secret_key:
  aes:
    ${SECRET_KEY}
